name: Build and Deploy

on:
  push:
    branches:
      - main  # spouštět při push do větve main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1) Checkout - stáhne kód do CI prostředí
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Nastavení Node verze (volitelné, ale často vhodné)
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3) Instalace závislostí
      - name: Install dependencies
        run: npm install

      # 4) Build projektu
      - name: Build
        run: npm run build

      # 5) Deploy na GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
